#!/usr/bin/tcsh -f
head -n 1 $1
tail +1 $1 | grep -v "%%%" | gawk '{if($4=="max"){nsum+=180;ncount++}else{psum+=$4;pcount++}}END{sum=psum+nsum;count=pcount+ncount; printf "Examples: %-8d  Succeses:  %-8d Failures:  %-8d\nTime:     %8.2f Positive: %8.2f  Remaining: %8.2f\n",count,pcount,ncount,sum,psum,nsum}'
