#!/usr/bin/csh

if($1 == "") then
   echo "Error: Need an argument (total_weight!"
   exit 1;
endif

date > ../report.total_$1
pwd >> ../report.total_$1
kb_create LAT_INC_KNOWLEDGE

foreach file   (\
ax_antisyma ax_antisymb ax_glb1a ax_glb1b ax_glb1c ax_glb1d ax_glb2a\
ax_glb2b ax_glb3a ax_glb3b ax_lub1a ax_lub1b ax_lub1c ax_lub1d\
ax_lub2a ax_lub2b ax_lub3a ax_lub3b ax_mono1a ax_mono1b\
ax_mono1c ax_mono2a ax_mono2b ax_mono2c ax_refla ax_reflb ax_transa\
ax_transb distrnu distrun lat1a lat1b lat2a lat2b lat3a lat3b lat4\
p01a p01b p02a p02b p03a p03b p03c p03d p04a p04b p04c p04d p05a p05b\
p06a p06b p06c p06d p07 p08a p08b p09a p09b p10 p11 p12 p12x p17a p17b\
p18 p19 p20 p20x p21 p21x p22a p22b p23 p23x p33 p38a p38b p39a p39b\
p39c p39d p40a p8_9a p8_9b)

limit cputime 1000
ln -s ../$file
echo "discount2 -s -x c_global_learn -G 0 -T $1 -A 0 -R 0 -K LAT_INC_KNOWLEDGE $file"
echo "discount2 -s -x c_global_learn -G 0 -T $1 -A 0 -R 0 -K LAT_INC_KNOWLEDGE $file" >> ../report.total_$1
if( { discount2 -s -x c_global_learn -G 0 -T $1 -A 0 -R 0 -K LAT_INC_KNOWLEDGE $file } ) then
   echo "Erfolg! "
   tail -28 $file.0 | head -1 >> ../report.total_$1
   tail -21 $file.0 | head -2 | cut -c40- | cut -c -11 | cat - run_bc_ops | dc >> ../report.total_$1
   unlimit
   pcl2 -F revert -s -x c_global_learn -G 0 -T $1 -A 0 -R 0 -K LAT_INC_KNOWLEDGE $file
   kb_insert -k LAT_INC_KNOWLEDGE $file.xtr
   mv $file.xtr ../GLOBAL_EXAMPLES/
else
   echo "Misserfolg! "
   echo XXX >> ../report.total_$1
   echo YYY >> ../report.total_$1
endif
rm $file.0 $file
echo --- >> ../report.total_$1
end
